"""Pydantic v2 data models used across all pipeline nodes."""

from __future__ import annotations

from pydantic import BaseModel, Field


class SearchQuery(BaseModel):
    """A single search query generated by the Intent Parser."""

    query: str = Field(description="The search string to send to the search API.")
    topic: str = Field(description="High-level topic this query relates to.")
    preferences: list[str] = Field(
        default_factory=list,
        description="User-stated preferences (e.g. 'recent', 'peer-reviewed').",
    )
    priority: str = Field(
        default="medium",
        description="Priority level: low, medium, or high.",
    )


class DiscoveredURL(BaseModel):
    """A URL returned by the search API."""

    url: str
    title: str = ""
    snippet: str = ""
    search_query: str = Field(
        default="", description="The query that surfaced this URL."
    )


class CrawledDoc(BaseModel):
    """Raw content fetched from a single URL."""

    url: str
    content: str
    word_count: int = 0
    crawl_method: str = Field(default="crawl4ai", description="'crawl4ai' or 'httpx'.")


class VerifiedSource(BaseModel):
    """A document that passed the source-verification step."""

    url: str
    content: str
    credibility_score: float = Field(ge=0.0, le=1.0)
    relevance_score: float = Field(ge=0.0, le=1.0)
    is_trusted: bool = False


class ExtractedEntity(BaseModel):
    """Specific entity extracted from a verified source."""

    name: str
    description: str
    metrics: dict[str, str] = Field(
        default_factory=dict,
        description="Dynamic key-value pairs of extracted public metrics.",
    )
    source_url: str
    priority_score: float = Field(
        default=0.0, description="0-1 match against user priorities."
    )
    original_content: str = ""
